baseurl: /pblog
title: Personal Blog
subtitle: Notes along the way
author: Dani Arribas-Bel
simple_search: http://google.com/search
description: Archive of personal blog
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Makefile', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
plugins: ['jekyll-paginate']
paginate: 7
paginate_path: "{{ site.baseurl }}/page:num/"
destination: "docs"
